disabled_rules:
- for_where
- unused_optional_binding
- mark
- todo
- trailing_whitespace
- redundant_string_enum_value
- function_body_length
- identifier_name
- type_name
- cyclomatic_complexity

included:

excluded:
- Pods
